services:
  db:
    restart: always
    image: mysql:latest
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: Banka 
    volumes:
      - banka-volume:/var/lib/mysql
  
  banka-backend:
    restart: always
    build: ../Backend/.
    ports:
      - "${DOCKER_WEB_PORT}:8080"
    env_file:
      - ../Backend/.env
    environment:
      DB_SERVER_ADDRESS: db
      DB_SERVER_PORT: 3306
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: Banka
    depends_on:
      - db 
  banka-frontend:
    restart: always
    depends_on:
      - banka-backend
    build: ../Frontend/.
    ports:
      - "${DOCKER_FRONTEND_PORT}:80"
    
volumes:
  banka-volume: