CREATE TABLE IF NOT EXISTS CreditAccount(
    UserID INTEGER NOT NULL,
    AccID INTEGER PRIMARY KEY UNIQUE,
    Balance INTEGER NOT NULL DEFAULT 0,
    MaturityDate DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);