CREATE TABLE IF NOT EXISTS Logs(
    LogID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    SrcAccID INTEGER NOT NULL,
    SrcAccType ENUM('Free', 'Saving', 'Credit') NOT NULL,
    DestAccID INTEGER NOT NULL,
    DestAccType ENUM('Free', 'Saving', 'Credit') NOT NULL,
    Amount INTEGER NOT NULL,
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Success BOOLEAN NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
);